# version: "3.9"
# services:
#   db:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_DATABASE: clinicabd
#       MYSQL_ROOT_PASSWORD:
#       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#     ports:
#       - "3307:3306"
#     volumes:
#       - db_data:/var/lib/mysql

#   web:
#     build: .
#     command: python run.py
#     volumes:
#       - .:/app
#     ports:
#       - "5000:5000"
#     environment:
#       - FLASK_ENV=development
#       - DATABASE_URL=mysql+pymysql://root@db:3306/clinicabd
#     depends_on:
#       - db

# volumes:
#   db_data:
version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: clinicabd
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: ["/bin/bash", "-c", "chmod +x ./wait-for-it.sh && ./wait-for-it.sh db:3306 -- python run.py"]
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/clinicabd
    depends_on:
      - db

volumes:
  db_data: